'''To implement GUI Frame Application using tkinter'''
from tkinter import *
import sqlite3


def Vote():
    root1=Tk()
    root1.title("Voters Application")
    p1=Page1(root1)
    root1.mainloop()
def Candidate():
    root2=Tk()
    root2.title("Candidate Application")
    p2=Page2(root2)
    root2.mainloop()

class Main: 
    def __init__(self,root):
        self.f1=Frame(root,height=600, width=600)
        self.f1.propagate(0)
        self.f1.pack()
        self.f1.configure(background='light blue')
        '''self.c=Canvas(self.f1,height=300,width=300,bg="red")
        self.file1=PhotoImage(file="abc.png")
        self.i1=self.c.create_image(100,40,anchor=N,image=self.file1)'''
        self.label1=Label(self.f1,text="WELCOME TO",font=('Elephant',50,'bold'),fg='RED',bg='light blue').place(x=10,y=20)
        self.label2=Label(self.f1,text="ELECTION 2018",font=('Arial Black',50,'bold'),fg='RED',bg='yellow').place(x=8,y=150)
        self.label3=Label(self.f1,text="Are you Voter?",font=('Harlow Solid Italics',20,'bold italic'),fg='Red',bg='light blue').place(x=100,y=300)
        self.label4=Label(self.f1,text="Click here:",font=('Arial Black',18,'bold'),fg='black',bg='light blue').place(x=100,y=350)
        self.button1=Button(self.f1,text="Voter",width=15,bd=5,fg='blue4',font=('Arial Black',18,'bold'),command=Vote,activeforeground='black')   
        self.button1.place(x=300,y=350)
        self.label3=Label(self.f1,text="Want to register for Election?",font=('Harlow Solid Italics',20,'bold italic'),fg='Red',bg='light blue').place(x=100,y=450)
        self.label3=Label(self.f1,text="Click here:",font=('Arial Black',18,'bold'),fg='black',bg='light blue').place(x=100,y=500)
        self.button2=Button(self.f1,text="Candidate",width=15,bd=5,font=('Arial Black',18,'bold'),fg='blue4',activeforeground='black',command=Candidate)   
        self.button2.place(x=300,y=500)
    
class Page1:
    def __init__(self,root1):
        self.root1=root1
        self.f=Frame(self.root1,height=2000,width=2000)
        self.f.propagate(0)
        self.f.pack()
        self.f.configure(background='light blue')
        '''self.c=Canvas(self.f,height=300,width=300,bg="red")
        self.file1=PhotoImage(file="abc.png")
        self.i1=self.c.create_image(100,40,anchor=N,image=self.file1)'''
        self.ev1=StringVar()
        self.ev2=StringVar()
        self.ev3=StringVar()
        self.l=Label(self.f,text="Voters Information",font=('Elephant',30,'bold'),fg='Red',bg='light blue').place(x=600,y=10)
        self.l1=Label(self.f,text="Enter PID",font=('Arial Black',14,'bold'),bg='light blue').place(x=100,y=100)
        self.l2=Label(self.f,text="Enter Name",font=('Arial Black',14,'bold'),bg='light blue').place(x=100,y=200)
        self.l3=Label(self.f,text="Enter Age",font=('Arial Black',14,'bold'),bg='light blue').place(x=100,y=300)
        self.l4=Label(self.f,text="Enter Gender",font=('Arial Black',14,'bold'),bg='light blue').place(x=100,y=400)
        self.l5=Label(self.f,text="Enter Candidate",font=('Arial Black',14,'bold'),bg='light blue').place(x=100,y=500)
        self.e1=Entry(self.f,width=28,font=('Arial',12),textvariable=self.ev1)
        self.e1.place(x=300,y=100)  
        self.e2=Entry(self.f,width=28,font=('Arial',12),textvariable=self.ev2)
        self.e2.place(x=300,y=200)
        self.e3=Entry(self.f,width=28,font=('Arial',12),textvariable=self.ev3)
        self.e3.place(x=300,y=300)
        self.vvar1=StringVar()
        self.vvar1.set("SELECT")
        self.s=OptionMenu(self.f,self.vvar1,"Male","Female")
        self.s.place(x=300,y=400)
        self.var=StringVar()
        self.var.set("SELECT")
        self.s1=OptionMenu(self.f,self.var,"Trupti","Rachel","Rhea","Voleta")
        self.s1.place(x=300,y=500)
        self.b1=Button(self.f,text="Check",width=15,bd=5,command=self.display)
        self.b1.place(x=100,y=600)
        self.b2=Button(self.f,text="Reset",width=15,bd=5,command=self.reset)
        self.b2.place(x=275,y=600)
        self.b3=Button(self.f,text="Submit",width=15,bd=5,command=self.insert)
        self.b3.place(x=440,y=600)
    def display(self):
        str1=self.e1.get()
        str2=self.e2.get()
        str3=self.e3.get()
        str4=self.vvar1.get()
        str5=self.var.get()
        l6=Label(self.f,text="Details entered are",font=('Arial Black',18,'bold'),fg='red',bg='light blue').place(x=1000,y=100)
        l7=Label(self.f,text="Your PID is: "+str(str1),font=('Verdana',15,'bold'),bg='light blue').place(x=800,y=200)
        l8=Label(self.f,text="Your name is: "+str(str2),font=('Verdana',15,'bold'),bg='light blue').place(x=800,y=300)
        l9=Label(self.f,text="Your age is: "+str(str3),font=('Verdana',15,'bold'),bg='light blue').place(x=800,y=400)
        l10=Label(self.f,text="Your Gender is: "+str(str4),font=('Verdana',15,'bold'),bg='light blue').place(x=800,y=500)
        l11=Label(self.f,text="Candidate chosen: "+str(str5),font=('Verdana',15,'bold'),bg='light blue').place(x=800,y=600)
    def insert(self):
        self.conn=sqlite3.connect("Election.db")
        self.cur=self.conn.cursor()
        self.cur.execute("create table if not exists Voter(PID varchar(20) unique, Name varchar(20) , Age varchar(20),Gender varchar(20),Candidate varchar(20))")
        print(self.cur.fetchall())
        str1=self.e1.get()
        str2=self.e2.get()
        str3=self.e3.get()
        str4=self.vvar1.get()
        str5=self.var.get()
        sql1="insert into Voter values('%s','%s','%s','%s','%s')"%(str1,str2,str3,str4,str5)
        self.cur.execute(sql1)
        print(self.cur.fetchall())
        self.cur.execute("select * from Voter")
        print(self.cur.fetchall())
    def reset(self):
        self.e1.delete(0,END)
        self.e2.delete(0,END)
        self.e3.delete(0,END)
        self.vvar1.set(" ")
        self.var.set(" ")
 
    
class Page2:
    def __init__(self,root2):
        self.root2=root2
        self.f=Frame(self.root2,height=2000,width=2000)
        self.f.propagate(0)
        self.f.pack()
        self.f.configure(background='pink')
        #c=Canvas(f,height=2000,width=2000,bg='light blue')
        #c.pack()
        '''file1=PhotoImage(file="abc.png")
        i1=c.create_image(10,2000, anchor=N,image=file1)'''
        self.ev1=StringVar()
        self.ev2=StringVar()
        self.ev3=StringVar()
        self.l=Label(self.f,text="Candidates Information",font=('Elephant',30,'bold'),fg='Red',bg='light blue')
        self.l.place(x=500,y=10)
        self.l1=Label(self.f,text="Enter PID",font=('Arial Black',14,'bold'),bg='light blue')
        self.l1.place(x=100,y=100)
        self.l2=Label(self.f,text="Enter Name",font=('Arial Black',14,'bold'),bg='light blue')
        self.l2.place(x=100,y=200)
        self.l3=Label(self.f,text="Enter Age",font=('Arial Black',14,'bold'),bg='light blue')
        self.l3.place(x=100,y=300)
        self.l4=Label(self.f,text="Enter Gender",font=('Arial Black',14,'bold'),bg='light blue')
        self.l4.place(x=100,y=400)
        self.l5=Label(self.f,text="Enter Year",font=('Arial Black',14,'bold'),bg='light blue')
        self.l5.place(x=100,y=500)
        self.e1=Entry(self.f,width=28,font=('Arial',12))
        self.e1.place(x=300,y=100)  
        self.e2=Entry(self.f,width=28,font=('Arial',12))
        self.e2.place(x=300,y=200)
        self.e3=Entry(self.f,width=28,font=('Arial',12))
        self.e3.place(x=300,y=300)
        self.vvar1=StringVar()
        self.vvar1.set("SELECT")
        self.s=OptionMenu(self.f,self.vvar1,"Male","Female")
        self.s.place(x=300,y=400)
        self.var=StringVar()
        self.var.set(" ")
        self.s1=OptionMenu(self.f,self.var,"SE","TE","BE").place(x=300,y=500)
        self.b1=Button(self.f,text="Check",width=15,bd=5,command=self.display).place(x=100,y=600)
        self.b2=Button(self.f,text="Reset",width=15,bd=5,command=self.reset).place(x=275,y=600)
        self.b3=Button(self.f,text="Submit",width=15,bd=5,command=self.insert).place(x=440,y=600)
    def display(self):
        str1=self.e1.get()
        str2=self.e2.get()
        str3=self.e3.get()
        str4=self.vvar1.get()
        str5=self.var.get()
        l6=Label(self.f,text="Details entered are",font=('Arial Black',18,'bold'),fg='red',bg='light blue').place(x=1000,y=100)
        l7=Label(self.f,text="Your PID is: "+str(str1),font=('Verdana',15,'bold'),bg='light blue').place(x=800,y=200)
        l8=Label(self.f,text="Your name is: "+str(str2),font=('Verdana',15,'bold'),bg='light blue').place(x=800,y=300)
        l9=Label(self.f,text="Your age is: "+str(str3),font=('Verdana',15,'bold'),bg='light blue').place(x=800,y=400)
        l10=Label(self.f,text="Your Gender is: "+str(str4),font=('Verdana',15,'bold'),bg='light blue').place(x=800,y=500)
        l11=Label(self.f,text="Year: "+str(str5),font=('Verdana',15,'bold'),bg='light blue').place(x=800,y=600)
    def insert(self):
        self.conn=sqlite3.connect("Election.db")
        self.cur=self.conn.cursor()
        self.cur.execute("create table if not exists Candidate(PID varchar(20) unique, Name varchar(20) , Age varchar(20),Gender varchar(20),Year varchar(20))")
        print(self.cur.fetchall())
        str1=self.e1.get()
        str2=self.e2.get()
        str3=self.e3.get()
        str4=self.vvar1.get()
        str5=self.var.get()
        sql1="insert into Voter values('%s','%s','%s','%s','%s')"%(str1,str2,str3,str4,str5)
        self.cur.execute(sql1)
        print(self.cur.fetchall())
        self.cur.execute("select * from Voter")
        print(self.cur.fetchall())
    def reset(self):
        self.e1.delete(0,END)
        self.e2.delete(0,END)
        self.e3.delete(0,END)
        self.vvar1.set(" ")
        self.var.set(" ")


root=Tk()#create root window
root.title("ELECTIONS 2018")
main=Main(root)#creating an object to class
root.mainloop()#root window handles the mouse events


